import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { SiTwitter } from "react-icons/si";
import {
  RiHome8Fill,
  RiNotification2Line,
  RiMailLine,
  RiBookmarkLine,
  RiFileListLine,
  RiUserLine,
  RiHeart3Line,
  RiChat1Line,
  RiMoreLine,
  RiSearch2Line,
} from "react-icons/ri";
import { RxUpload } from "react-icons/rx";
import { BiHash } from "react-icons/bi";
import { CgMoreO } from "react-icons/cg";
import { HiOutlineSparkles } from "react-icons/hi";
import { AiOutlineRetweet } from "react-icons/ai";
import Image from "next/image";
const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto grid h-screen w-10/12 grid-cols-3">
        <LeftSide />
        <Middle />
        <RightSide />
      </main>
    </>
  );
};

const LeftSide = () => {
  return (
    <div className="w-1/2 justify-self-end border-r border-slate-700">
      <section className="sticky top-0 flex h-screen flex-col justify-between">
        <div className="flex  flex-col  text-white">
          <Link href="/home" className="my-1">
            <span className="rounded-3xl border-slate-400 py-3 pl-4 text-xl  ">
              <SiTwitter className="mr-4 inline-block h-6 w-6" />
            </span>
          </Link>
          <Link href="/home" className="my-1">
            <button className="rounded-3xl border-slate-400 py-3 pl-4  pr-6 text-xl  hover:bg-zinc-900">
              <RiHome8Fill className="mr-4 inline-block h-6 w-6" />
              Home
            </button>
          </Link>
          <Link href="/home" className="my-1">
            <button className="rounded-3xl border-slate-400 py-3 pl-4  pr-6 text-xl  hover:bg-zinc-900">
              <BiHash className="mr-4 inline-block h-6 w-6" />
              Explore
            </button>
          </Link>
          <Link href="/home" className="my-1">
            <button className="rounded-3xl border-slate-400 py-3 pl-4  pr-6 text-xl  hover:bg-zinc-900">
              <RiNotification2Line className="mr-4 inline-block h-6 w-6" />
              Notifications
            </button>
          </Link>
          <Link href="/home" className="my-1">
            <button className="rounded-3xl border-slate-400 py-3 pl-4  pr-6 text-xl  hover:bg-zinc-900">
              <RiMailLine className="mr-4 inline-block h-6 w-6" />
              Messages
            </button>
          </Link>
          <Link href="/home" className="my-1">
            <button className="rounded-3xl border-slate-400 py-3 pl-4  pr-6 text-xl  hover:bg-zinc-900">
              <RiBookmarkLine className="mr-4 inline-block h-6 w-6" />
              Bookmarks
            </button>
          </Link>
          <Link href="/home" className="my-1">
            <button className="rounded-3xl border-slate-400 py-3 pl-4  pr-6 text-xl  hover:bg-zinc-900">
              <RiFileListLine className="mr-4 inline-block h-6 w-6" />
              Lists
            </button>
          </Link>
          <Link href="/home" className="my-1">
            <button className="rounded-3xl border-slate-400 py-3 pl-4  pr-6 text-xl  hover:bg-zinc-900">
              <RiUserLine className="mr-4 inline-block h-6 w-6" />
              Profile
            </button>
          </Link>
          <Link href="/home" className="my-1">
            <button className="rounded-3xl border-slate-400 py-3 pl-4  pr-6 text-xl  hover:bg-zinc-900">
              <CgMoreO className="mr-4 inline-block h-6 w-6" />
              More
            </button>
          </Link>
          <button className=" mx-2 mr-8 mt-6 rounded-3xl bg-sky-500 py-3 text-xl hover:bg-sky-600">
            Tweet
          </button>
        </div>
        <button className="m-4 flex rounded-full border-slate-700 p-4 hover:bg-zinc-900">
          <div className="h-100 ">
            <Image
              src="https://randomuser.me/api/portraits/lego/8.jpg"
              alt="User Image"
              width={50}
              height={50}
              className="rounded-full"
            />
          </div>
          <div className="ml-4 flex w-full font-bold text-white">
            <p>User</p>
          </div>
          <RiMoreLine className="mr-4 inline-block h-10 w-10 text-white" />
        </button>
      </section>
    </div>
  );
};

const RightSide = () => {
  return (
    <div className="w-1/2 border-l border-slate-700">
      <section className="sticky top-0  mx-4 flex h-screen flex-col justify-between">
        <div className="flex flex-col  text-white">
          <div className="my-2">
            <RiSearch2Line className="absolute left-3 top-4 h-6 w-6 text-zinc-500 " />
            <input
              type="text"
              name="search"
              id="search"
              placeholder="Search Twitter"
              className="rounded-full bg-gray-800 py-2 pl-12 pr-5 outline-none placeholder:text-zinc-500  focus:border-sky-500 focus:outline-sky-500"
            />
          </div>
        </div>
      </section>
    </div>
  );
};

const Middle = () => {
  return (
    <section>
      <div className="sticky top-0 flex items-center justify-between bg-black bg-opacity-75 py-4 pl-4 text-xl text-white backdrop-blur-xl">
        <span>Home</span>
        <HiOutlineSparkles className="mr-4 h-6 w-6" />
      </div>
      <div className="">
        {Array(...Array(20)).map((x, i) => {
          return <Tweet key={i} />;
        })}
      </div>
    </section>
  );
};

const Tweet = () => {
  return (
    <div className="flex border-b border-slate-700 p-4">
      <div className="h-100 ">
        <Image
          src="https://randomuser.me/api/portraits/lego/8.jpg"
          alt="User Image"
          width={50}
          height={50}
          className="rounded-full"
        />
      </div>
      <div className="ml-4 flex w-full flex-col">
        <p className="font-bold text-white">User</p>
        <p className="text-white">
          Textjkasdflkjasdhnl fkjsadhflksjadhfnasldkjfh lskdajfh lksjdhf lksdjhf
          a;lsdkf ;lsdkf;l sdkf'; lksd;lfksd;l fksd;lf slkdjfl;k sdjfklsadj
          flaksdjfh sldkj ksjadhflkajsd hfkajsd Textjkasdflkjasdhnl
          fkjsadhflksjadhfnasldkjfh lskdajfh lksjdhf lksdjhf a;lsdkf ;lsdkf;l
          sdkf'; lksd;lfksd;l fksd;lf slkdjfl;k sdjfklsadj flaksdjfh sldkj
          ksjadhflkajsd hfkajsd Textjkasdflkjasdhnl fkjsadhflksjadhfnasldkjfh
          lskdajfh lksjdhf lksdjhf a;lsdkf ;lsdkf;l sdkf'; lksd;lfksd;l fksd;lf
          slkdjfl;k sdjfklsadj flaksdjfh sldkj ksjadhflkajsd hfkajsd
        </p>
        <div className="flex justify-between pt-2 text-slate-600">
          <button className=" hover:text-sky-500 ">
            <RiChat1Line className="mr-2 inline-block h-7 w-7 rounded-full p-1 hover:bg-sky-900 hover:bg-opacity-30" />
            25
          </button>

          <button className="hover:text-green-500">
            <AiOutlineRetweet className="mr-2 inline-block h-7 w-7 rounded-full p-1 hover:bg-green-900 hover:bg-opacity-30" />
            24
          </button>

          <button className="hover:text-red-500">
            <RiHeart3Line className="mr-2 inline-block h-7 w-7 rounded-full p-1 hover:bg-red-900 hover:bg-opacity-30" />
            24
          </button>

          <button className="mr-16 hover:text-sky-500 ">
            <RxUpload className="mr-2 inline-block h-7 w-7 rounded-full p-1 hover:bg-sky-900 hover:bg-opacity-30" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;
